version: 2
updates:
  - package-ecosystem: github-actions
    directory: /
    schedule:
      interval: monthly
  - package-ecosystem: swift
    directory: /TibberMenuBar
    schedule:
      interval: monthly
